### ISSUE TITLE
Feed stripe payments into our database

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#105]
Every time we receive an stripe payment I have to input it manually to our Income table. There must be an easy way to integrate with them and ad that info automatically in GBP as a donation, reserving for loans 50%

**Comment by marcosmenendez** [comment]
I've made a stripe donation and haven't seen the income in the webapp. @atrandafir please fix it. Talk to @bodiapz first if you need to understand what has been done

**Comment by atrandafir** [comment]
@marcosmenendez a few questions regarding this task:

1. Why only Stripe payments?

Shouldn't all the donations no matter what payment method used, be considered a income?

And also, as far as I remember, on the "Get your share" page you can choose buy share and make donation at the same time. Shouldn't this case also be considered a income? I mean with 10gbp 0.01 goes for share and 9.99 for donation.

2. When adding the income, shouldn't we be able to detect how much of it was considered "expense" and store also the expense? For example the % fee that goes to Stripe.

3. Last one, shouldn't we convert the Currency the user has choosen into GBP for the income? I mean the user can now choose USD,BTC,EUR,GBP.

**Comment by marcosmenendez** [comment]
Stripe is our only platform to date besides bitcoin, which is marginal.

I was just talking about pure donations https://www.thegooddata.org/support-us, not share purchase. In case of the share purchase it already works as you mention.

I'm not sure if Stripe API provides both the gross income and the expense. Use whatever info stripe provide. At this point we are enjoying an offer that takes out any expense from stripe payments.

Alex, most of your questions would have been solved by simply going through the donation process.

**Comment by atrandafir** [comment]
Update: We've agreed with @marcosmenendez that this will be done by looking for info in Stripe API instead of touching anything in the donation process pages. So we can create a command that will download that info from Stripe and configure it as a cronjob.

**Comment by UchihaCFC** [comment]
Can I do a command that later can be configured to stripe, but still need to know what table database, @marcosmenendez  saves the data manually to save automatically now, once down the information from the api Stripe payment. Its the correct process @atrandafir ?

**Comment by marcosmenendez** [comment]
I don't know the name of the table. I fill out this form: https://www.thegooddata.org/incomes/create

I copy the income date, gross amount in GBP and the expenses from Stripe (although they are not charging any at this point) 
I mark the income as donation, assign 50% to microloans and name it as "Stripe YYMMDD"

Regarding Stripe, I guess we can get that data using their API https://stripe.com/docs/libraries. It would be enough if we get that data once a day, since there are very few payments

**Comment by jorgeheavydots** [comment]
This is ready to test, cron job is set to execute everyday at 0:00, to test manually use:

php yiic.php GetDonationsFromApi

**Comment by marcosmenendez** [comment]
There were 2 bugs here:
1. We imported payments that were already in our backend so there was some double counting. I deleted them
2. We imported those payments in USD instead of GBP. For instance, the payment of September 9th was  35 USD, we should have imported the amount in GBP that was 9.48 according to Stripe. I changed that amount manually. Can we fix this for future payments?

Thanks
