### ISSUE TITLE
"Start" message at good-data persists

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#107]
The message shown in yellow at the top of the screen should not be shown again if the user clicks on the "x". Now, if users visit that url again, the message is shown, even if it has been deleted before

**Comment by JuanMenendezBuitrago** [comment]
@atrandafir Should we use the ExtensionSettings model+table to store this preference as we do with the "store navigation" extension option? Or should we create another model+table to store webapp user settings ?

**Comment by atrandafir** [comment]
First of all, should we remove that? I mean, it doesn't look bad to me, the message that it displays I think it could be a fixed part of that page, not an optional one, what do you think @marcosmenendez ?

I personally like the message and we could just remove the close button and leave it always visible.

But if you think it should not be there forever we should either:
1) Don't show it again per session (store a session variable to hide it on the next page load)
2) Don't show it never again (store it as user preference in the database)

In case of the second option, I would create a separate table for that, either similar structure as "ExtensionSettings" to allow infinite settings, or a table with one field per each setting.

**Comment by marcosmenendez** [comment]
Can we just keep that info in the cookie? Please, make it simple

**Comment by bodiapz** [comment]
As you said, I used cookie
