### ISSUE TITLE
Evil data page is not optimised

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#109]
When visiting the evil-data page, it takes several minutes to display the info. This unacceptable.

Lets evaluate all possibilities:
1. Caching some calculations (individual and company averages)
2. Calculating some of them in cron routines at off-peak time
3. Discarding to present some of those numbers, or present some others that are easier to calculate

**Comment by bodiapz** [comment]
The main problem in table tpl_browsing. Need to add indexes for this table. And the results will appear much faster. Also I've noticed couple more problems in DB normalization. This is bottleneck.

In fact, we often use domains in different tables. There a lot of duplicate records. Need to create new table with domains, and in all other tables we should use only ids. 

It's allow to save a lot of space, loading time. But need to review the code. And better to do this in earlier stages.

**Comment by marcosmenendez** [comment]
Let's do at least the indexing now. If you prefer leaving the rest until you feel more comfortable with the code, I'm happy either way.

If you change the names of the variables, I'd like to review them with you first. Some of them are written in a poor English and I would like to take the opportunity to correct them if possible. Not a big issue at all, but would like to do it if there is the chance
