### ISSUE TITLE
Remember sign in by default

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#112]
In the sign-in page there is a check box saying "Remember me". That box should be checked by default. https://www.thegooddata.org/sign-in

Sign-in from the extension does not have this check box, so should always remember the user unless he signs out

**Comment by JuanMenendezBuitrago** [comment]
Just to be sure that I've understood. You just want to have the "remember me" option checked by default in the sign-in form, right?

I mean, the other thing you mentioned about having the extension always remember the user unless he/she explicitly signs-out, it's the current  behavior we have already implemented, isn't it? (I have signed in using the extension, closed the browser and reopened it and I was still signed in). It's working differently for you?

**Comment by marcosmenendez** [comment]
I didn't know about how the extension behaves. If this is the case, then yes, just check by default the web sign-in form
