### ISSUE TITLE
Request for user email in case of Firefox or Safari

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#113]
At this point when a user ask to Get TheGoodData from a non-Chrome browser, he show a message saying that we are not yet there. We should as instead for his email.

This email will feed a segment in PHPlist called Firefox or Safari depending on the browser.

For other desktop browsers and all mobile browsers we will keep current message

**Comment by JuanMenendezBuitrago** [comment]
OK, I've been figuring out how to implement this and other similar issues and I'm almost done with it. what I need to know is what you understand as "segment" as I can't find anything called "segment" in PHPList. Do you mean that the user email should be added to a list depending on the browser he/she is using (either to a Firefox list or to a Safari list) so that they can be notified in the future when there's a solution for their browser?

**Comment by marcosmenendez** [comment]
Yes, they call them lists. I've created the 2 lists already

**Comment by JuanMenendezBuitrago** [comment]
This issue is implemented in pre. I've created two lists (Safari - test and Firefox - test) in PHPList in order to make the tests.

**Comment by marcosmenendez** [comment]
@JuanMenendezBuitrago this is not working. I first put a text (not email) and nothing happened after the send. Then I put an email and the form was coloured like if something was happening but without any text asking to wait and with anything actually happening after several minutes. Screenshot attached.

![screen shot 2015-03-07 at 10 46 46 am](https://cloud.githubusercontent.com/assets/1178350/6540910/90b392a8-c4b7-11e4-8a2d-822ea08abb67.png)

**Comment by JuanMenendezBuitrago** [comment]
I've tested for empty values and wrong format strings  and it works fine. I would suggest to change the message shown after a successful submission for something more suitable.

**Comment by marcosmenendez** [comment]
It works now, but it didn't before, so I suggest setting a time-out (10 secs) and a message saying "Opps, something went wrong. Please try again later."

Regarding the success message, use the same we had for early access:

"Thanks!

We'll send you an invite once we're ready.
For frequent updates, follow us @thegooddata"

**Comment by JuanMenendezBuitrago** [comment]
I've deployed to pre and tested for errors and successful cases. Everything looked fine but some fresh eyes will be appreciated.

**Comment by marcosmenendez** [comment]
In safari I entered an address without a proper email format, I got the error message. Then I wrote a proper address, clicked on submit and nothing happened.

Only submitted after refreshing the page and entering the right format at the first place

**Comment by JuanMenendezBuitrago** [comment]
I've tried the same but t worked for me. I will try several times in order to track down the cause of problem. There's a timeout of 10 seconds in case something doesn't work. Did you wait  10 seconds and no error message was shown?

**Comment by marcosmenendez** [comment]
I didn't wait so long, however It worked for me now, so assume i did something wrong. Marked as ready to deploy

**Comment by atrandafir** [comment]
Tested with Firefox locally and in Pre.
