### ISSUE TITLE
Finetune new blog theme

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#114]
We have set up a new theme DW minion, but the following things need to be fine tuned:
1. Move calendar widget from left to right column. If I do it myself, other default widgets appear on the left.
2. Make links look blue by default (the same blue we use in our main site). Explained here: http://www.designwall.com/question/how-do-i-change-my-link-colours-on-the-entire-site/
3. Video screenshots are not seen. If you go to https://blog.thegooddata.org/2015/02/in-your-place/ There should be 3 screenshots at the bottom, but they cannot be seen (at least in my chrome browser)
4. We should try to use our own fonts. Read here about how to change them to proxima nova. If you need Proxima Nova files, please ask http://www.designwall.com/question/how-to-change-font-css-on-dw-minion/
5. Change footer with standard one
6. Make that logo in the top sends users to www instead to the blog
7. There seems to be piwik code both in the header and footer. Could you check that it is only in one place? (wherever it is configured to be by piwik plugin

Please try to do this changes using theme settings, or the editor under appearance option (I think changes are usually grouped in a custom file, but not sure). Check if issues are answered here first: http://www.designwall.com/blog/question/

**Comment by atrandafir** [comment]
Note, there's a SSL issue with loading fonts.

We should specify font url with https. Or without protocol. '//'

**Comment by JuanMenendezBuitrago** [comment]
Are these the video screenshots that should be shown?

![capture-blog](https://cloud.githubusercontent.com/assets/5305439/6041691/0ac81948-ac7f-11e4-9eb9-d53872dec98d.png)

**Comment by marcosmenendez** [comment]
Yes I added youtube iframe manually, because if pasted directly the youtube
url, video was not correctly embadded. However we can skip that bug about
the videos, since there is a workaround



*Marcos Menendez*
hangout: marcos@thegooddata.org
skype: marcosmenendez
tel: +44 (0)20 3289 0009
twitter: @marcmenen <https://twitter.com/intent/user?screen_name=marcmenen>
Unit 1, 82 Clerkenwell Road
London EC1M 5RF

**Comment by marcosmenendez** [comment]
A couple of comments:
- Title font in the detail page is still the old one. See here: https://blog.thegooddata.org/2015/02/putting-us-in-your-place/
- Regarding point 6, I've changed again the url of the blog in general settings, because if not all the url's were wrong. For instance the above one would have started with www
- Regarding 1, archive (not calendar) is the widget that has to be moved to the right

**Comment by JuanMenendezBuitrago** [comment]
Some changes can't be done without touching the files. Maybe creating a theme based on the current one but I would have to learn whether that's possible or not and how to do that. Check the design as it  is right now and tell me if it's correct.

**Comment by marcosmenendez** [comment]
It is fine as it is for now. Could you just undo one thing? I've seen that there is no way now to go back to the blog home, so we better point TGD icon to blog, instead of www.

With that, it can be closed

**Comment by marcosmenendez** [comment]
We are not using the same colour palette as in our website. Blue links in the blog are darker than in the website. Default grey text colour in the blog is also brighter than in the website, so it is hard to differentiate between text and links.

To get the right colour of the links and texts use for instance this page were there is a link to disconnect.me https://www.thegooddata.org/product

**Comment by JuanMenendezBuitrago** [comment]
I've changed the colors in links and body to match the webapp. I thought we were talking about the other blue. The blue in the logo. Or do you want me to use the dark blue for the titles and a lighter blue for the links?

**Comment by marcosmenendez** [comment]
Something that is consistent with the site and looks good

**Comment by marcosmenendez** [comment]
I've seen that we have installed a plugin called "use any font" This plugin inserts 3 Automatic cookies. Can we do whatever this plugin does without adding more cookies to the blog?

**Comment by JuanMenendezBuitrago** [comment]
I thought this plugin was disabled. It's not necessary so I removed it.
