### ISSUE TITLE
Test evil data with plenty information

### ISSUE THREAD

**Issue by atrandafir** [thegooddata/webapp#117]
We should test the Evil data page again with a user that has a lot of information.

Once we see the results we should make review and a proposal for the modifications required in order to provide decent loading times on this stats page.

**Comment by bodiapz** [comment]
I've tested 1.8 million records. So, in fact, calculation takes 4 seconds. 
This calculation caching for user. It means, the user will have this delay only once per day. All other calculations (cached) will be performed at 200 ms. 
I suggest add cron job, to calculate this data. But I need to know when we have low loading

**Comment by marcosmenendez** [comment]
Optimization effort has been focused on the domains visited.

Same to be done with the rest of the tables requested in that page: adtracks, search queries, etc Probably some more indexes need to be built.

Other optimization actions (like calculation of daily totals) will be addressed in separate topics like #124
