### ISSUE TITLE
Return to first page on "Sites visited"

### ISSUE THREAD

**Issue by agonbar** [thegooddata/webapp#119]
![image](https://cloud.githubusercontent.com/assets/1553211/6043462/9c87d6e0-ac8c-11e4-8ef3-8589e585e6aa.png)

**Comment by agonbar** [comment]
There's a missing **1 ...** 19 20 21 22 23 ... 25

**Comment by marcosmenendez** [comment]
I assume it is tested (I cannot test in pre since there is no data), but it is not closed since it is not in production. So reopen it until deployed
