### ISSUE TITLE
Send all mails via Amazon

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#122]
Currently, mails to users and admin are sent via zoho smtp. This is not the best option, since many time those mails end up in the spam folder.

Change smtp settings to SES or use mail command to send them via postfix

**Comment by JuanMenendezBuitrago** [comment]
@agonbar , @atrandafir : Are we Amazon EC2 users? or do we have  a smtp server running in our server? I either case I would need to know the credentials to change the configuration in config.php.

**Comment by atrandafir** [comment]
@JuanMenendezBuitrago I have no idea if we have Amazon EC2 account. Maybe @marcosmenendez  knows better if we do or don't.

As for now as Marcos says, we're using Zoho smtp. As for local SMTP I don't know if we have it.

**Comment by marcosmenendez** [comment]
I've shared with @JuanMenendezBuitrago  Amazon SES credentials

**Comment by marcosmenendez** [comment]
shared/config.php file changed and commented in pro. @atrandafir to accept commented changes and close the issue
