### ISSUE TITLE
Problem uploading images

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#123]
If I want to edit a loan details, image is not properly shown in the admin view (although it is shown in the users view). See here https://www.thegooddata.org/loans/update/11

If I want to upload the image again, I receive the following error:
![screen shot 2015-02-17 at 9 43 57 am](https://cloud.githubusercontent.com/assets/1178350/6225378/94d36480-b689-11e4-919a-1c4838dd7f8b.png)

**Comment by atrandafir** [comment]
Looks like a permissions issue, I would have @agonbar take a look at it.

**Comment by marcosmenendez** [comment]
@agonbar please take care of this. It is not extremely urgent, so we can wait till next week. Please be sure that we have no more issues with permissions

**Comment by agonbar** [comment]
To solve all the permission problems and improve the security, the best option would be to change all the ownership of all the web files to www-data.
In order for this to work the devs need to change the capistrano formula to do a "sudo su www-data" before each deploy, just at the beginning.
Please confirm as soon as possible to proceed or not with the change.

**Comment by agonbar** [comment]
As the devs decided to maintain the tgd user on deploys, the folders that need to be writen are set to 777 and the files to 644, thus solving the problems.
A note for the future, if another folder will be used for writting from the server, ask the sysadmins to set the permissions to 777 before using them.
