### ISSUE TITLE
Enable gzip for font files on nginx

### ISSUE THREAD

**Issue by atrandafir** [thegooddata/webapp#128]
This issue is related to #115

For each font we use there are three files, ttf, wof, eot but only one is loaded depending on browser support.

Woff is compressed by default but the other 2 tyes used by older browsers could benefit in download speed if the webserver uses gzip on them.

Found this tutorial explaining how to make nginx gzip the fonts:
http://blog.bigdinosaur.org/gzipping-at-font-face-with-nginx/

As for testing that it is working we can use this service:
http://www.whatsmyip.org/http-compression-test/

with this test url:
https://www.thegooddata.org/themes/tgd/fonts/2926A8_2_0.ttf

**Comment by agonbar** [comment]
Fixed and checked.
