### ISSUE TITLE
[blog] Change url of webfonts.css to load them from webapp

### ISSUE THREAD

**Issue by atrandafir** [thegooddata/webapp#129]
Right now we use the same fonts on webapp, blog and collaborate, but the font files are repeated in each application.

That means that a user visiting first webapp and then blog, and then collaborate, will load the fonts 3 times.

To avoid that we should modify the theme to load the css from webapp:
https://www.thegooddata.org/themes/tgd/css/vendor/webfonts.css

Instead of the one from the theme folder:
https://blog.thegooddata.org/wp-content/themes/dw-minion/assets/css/webfonts.css

With just loading this file I think the fonts should load properly but check it to be sure and let me know if there are any issues.

Related to: https://github.com/thegooddata/webapp/issues/115

**Comment by JuanMenendezBuitrago** [comment]
> Font from origin 'https://www.thegooddata.org' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://blog.thegooddata.org' is therefore not allowed access.

**Comment by atrandafir** [comment]
We've decided to not do this, so closing the issue.
