### ISSUE TITLE
[blog] requested an insecure stylesheet 'http://fonts.googleapis...'

### ISSUE THREAD

**Issue by atrandafir** [thegooddata/webapp#130]
If you open the blog with Chrome js console open you'll see the error in the title.

Cause by loading this over http instead of https:
@import url(//fonts.googleapis.com/css?family=Roboto:400,400italic,500,700);

@import url(http://fonts.googleapis.com/css?family=Roboto+Slab:700,400);

(from main.css)

The fix would be either:
1) Change urls to https:// if we will always work on https
2) Or maybe I think that removing the protocol and putting // will work on both http and https, example:
@import url(//fonts.googleapis.com/css?family=Roboto:400,400italic,500,700);

By the way first check if we're actually using that font in the blog since we're also using ProximaNova. If we don't use it we should remove it instead of fixing urls.

**Comment by JuanMenendezBuitrago** [comment]
I changed the imports to // alone removing the protocol.
