### ISSUE TITLE
Update phplist

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#131]
When logging in, php warns that there is a newer version of it. Not sure if it is worth upgrading or not, or if it is something that we can do in the web ourselves.

If not please go ahead. Check that everything works after update

**Comment by agonbar** [comment]
Updated.

**Comment by marcosmenendez** [comment]
Since update a phplist logo is attached at the end of every mail. We should take it out as it was before

**Comment by agonbar** [comment]
Ok, I'll make a document with the changes needed in each actualization to
prevent future problems.

**Comment by agonbar** [comment]
It should be removed, please do some tests with our e-mails while I try to solve the other problems and create the document. Thank you.

**Comment by agonbar** [comment]
https://docs.google.com/document/d/13WgJzxspkkY0AWgxws5a-8A-JTET3Eyl7lPdNivQq1c/edit?usp=sharing

That should resolve any problems with future updates in case I'm not present. I'll continue to write there the changes made in the code.

**Comment by agonbar** [comment]
The reinstall is finished, but the e-mail still doesn't work, which is strange as now it doesn't show any error at all and the relay with amazon SES is working, I''ve tested it with phplist.
I'll continue investigating once the deploy errors are solved.

**Comment by marcosmenendez** [comment]
Is this issue fixed? If so, please close

**Comment by calidadesystems** [comment]
Reconfigured mailserver, was a postfix miss configuration I send a test email and is comming from amazon

Jul 29 16:07:34 mail postfix/smtpd[29202]: connect from a6-173.smtp-out.eu-west-1.amazonses.com[54.240.6.173]
Jul 29 16:07:35 mail postgrey[648]: action=greylist, reason=new, client_name=a6-173.smtp-out.eu-west-1.amazonses.com, client_address=54.240.6.173, sender=0000014eda23c314-b3499378-0006-4f4d-8e91-0d6d964e1ed1-000000@eu-west-1.amazonses.com, recipient=info@calidadesystems.com
Jul 29 16:07:36 mail postfix/smtpd[29202]: NOQUEUE: reject: RCPT from a6-173.smtp-out.eu-west-1.amazonses.com[54.240.6.173]: 450 4.2.0 <info@calidadesystems.com>: Recipient address rejected: Greylisted for 60 seconds; from=<0000014eda23c314-b3499378-0006-4f4d-8e91-0d6d964e1ed1-000000@eu-west-1.amazonses.com> to=<info@calidadesystems.com> proto=ESMTP helo=<a6-173.smtp-out.eu-west-1.amazonses.com>
Jul 29 16:07:58 mail postfix/smtpd[29202]: disconnect from a6-173.smtp-out.eu-west-1.amazonses.com[54.240.6.173]
