### ISSUE TITLE
A couple of improvements with loans

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#133]
Whenever I save some new details in a loan, the last update date should be updated to that moment.

In the good data page, when the title of a loan is too long, the sector end ups falling beneath the picture, while it should be aligned with the title
![screen shot 2015-02-27 at 1 26 17 pm](https://cloud.githubusercontent.com/assets/1178350/6412483/afc3e6ae-be84-11e4-8246-87cd246fe608.png)

**Comment by JuanMenendezBuitrago** [comment]
Regarding the update date, there are two dates when viewing the loan details which I don't know if they're redundant: updated_at and loan_update. The one that get's updated every time that the loan is updated is updated_at. I don't know the purpose of the other one.

**Comment by marcosmenendez** [comment]
They are redundant. Keep the one that is automatically updated and include it in the loan view (not editable)

**Comment by JuanMenendezBuitrago** [comment]
I've deployed to pre and tested it. Created a a new loan, updated .. etc and everything looked right.

**Comment by marcosmenendez** [comment]
Tested and ready to deploy. @JuanMenendezBuitrago could you confirm that you have deleted unnecessary fields from the database or have you just hidden them from the form?
