### ISSUE TITLE
Existing user sessions not deleted when user account is blocked.

### ISSUE THREAD

**Issue by josereyero** [thegooddata/webapp#134]
When a user account is blocked/disabled, existing user sessions are not deleted, thus the user can still access the site provided he/she was previously logged in.

I've fixed this on the 'collaborate' side by checking account status for every page load, but I guess this should be fixed in the webapp too.

**Comment by atrandafir** [comment]
Indeed I believe there is no check on the database after the user is already logged in. 

We can add that to the user component, do a check on the user table and apply the same rules as in the login form.
