### ISSUE TITLE
Several mistakes in your-data page

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#135]
If you enter as an admin you will see that:
1. The number of pieces of data contributed shown in the webapp, is different than the number shown in  the extension. That happens because tha webapp only shows the number of data pieces traded AND stored, while the extension shows the number of pieces TRADED regardless if we store them or not. The extension number is the right one. Please be sure that this is the number we use to calculate the total number in "good-data" page as well
![screen shot 2015-03-02 at 10 40 11 am](https://cloud.githubusercontent.com/assets/1178350/6438499/cd62703a-c0c9-11e4-8fea-86d9fc35c4f5.png)
2. The pagination does not work properly. It allows you to jump to the last page, but if you want to go back to the first page there is no shortcut. You have to go back one by one. There should always be a link to the first and last page. Isn't there a default function to show it?
![screen shot 2015-03-02 at 10 43 04 am](https://cloud.githubusercontent.com/assets/1178350/6438544/58002124-c0ca-11e4-9617-98db21980dba.png)

3. Url is wrong. It says "user-data" when in should say "your-data" as the page title. Please amend it and update links:
a. In the extension
b. In the webapp menu
c. In the webapp drop down menu at the top right

**Comment by bodiapz** [comment]
Hi, can you check pagination once more because I think its working well.
![pagination](https://cloud.githubusercontent.com/assets/10200349/6458860/3a672078-c191-11e4-9a71-be6108165027.jpg)
If you see that pagination is wrong please tell me what browser you use.

**Comment by marcosmenendez** [comment]
If I jump directly from first page to last page, it does not show me again the first page
![screen shot 2015-03-03 at 9 58 06 am](https://cloud.githubusercontent.com/assets/1178350/6459132/da01d688-c18b-11e4-96d9-5b95799bad89.png)

**Comment by marcosmenendez** [comment]
I cannot test it without data. I pass it to @atrandafir to test or to fill with data

**Comment by marcosmenendez** [comment]
@atrandafir please remember to test this as well and mark it as ready to deploy

**Comment by JuanMenendezBuitrago** [comment]
@bodiapz , @atrandafir :I know this issue is closed but I am curious about the bug with the pagination since I was the one who tried to solve it in he first place.  Was there something wrong with it? I see nothing in he commit.
