### ISSUE TITLE
Changes in about-us page

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#138]
Before doing this issue, implement issue #137 

We should change the bottom part of the page, taking out the "our way" and including a new section as drawn hereafter with people's avatars linked to their webpage (if they have added it in their profile). It should display pictures of all members that have provided a picture on a pseudo-random order. Every time the user clicks on the "more" button at the bottom of the page, another 20 faces will be shown, up until there are no more faces to show
![about us page](https://cloud.githubusercontent.com/assets/1178350/6447972/df8383b0-c116-11e4-97ad-acae5b31962b.JPG)

With pseudo-random order I mean that in the first set of 20 faces the following should be presented on random order:
- all faces with "director" seniority
- at least 7 faces of users with "owner" or "expert owner" seniority
- as many collaborators as there are up to a maximum of 20-7-directors

If there are for instance 7 directors and 20 collaborators, the first set of faces would include:
- 7 owners and expert owners
- 7 directors
- 6 collaborators

The remaining 14 collaborators will be shown in the following sets, always leaving at least 7 for owners and expert owners. In this case, 13 collaborators would be presented in the second set and 1 in the third.

Pictures or avatars will be clickable if the user has provided a link, and will be surrounded by a frame with a different colour depending on the level of seniority

**Comment by marcosmenendez** [comment]
@bodiapz @atrandafir when we upload this issue to preproduction, can we do it on a separate branch? Since we will need some design done I wouldn't like that it blocks the other issues from being deployed.

This afects issue #136 as well

**Comment by marcosmenendez** [comment]
1. super users should not appear in the "people". It doesn't make sense to have a picture of an "admin"
2. I requested to leave the first paragraph in people, not the second one. Anyway, please put the following test: "TheGoodData is 100% owned by its users. Users become shareholders by simply requesting it. In doing so, TheGoodData interests will always be aligned with yours, which means we’ll never sell out to another company so your data will be safer with us."
3. I've asked to show 5 pictures per line, not sure if we are showing 4 or 5. Try not to make them smaller, reduce margins first
4. When clicking on a picture, link should be opened in a new tab, not in the same one
5. If there is no picture of a certain seniority (eg.Members) we should not show a legend for them at the top
6. I've said to show the username, but I've changed my mind, please take it out. Sorry

**Comment by marcosmenendez** [comment]
@bodiapz I don't understand anything. Pictures of members do not appear anymore in the about page.

Manual levels (collaborator and director) cannot be set either

Give me a call

**Comment by bodiapz** [comment]
Hmm.. I'm not sure what happens on pre-production. Checking...

**Comment by bodiapz** [comment]
I've corrected issues with upload. Problem was in permissions. Now need to upload avatars and then they apear on this page

Seniority levels fixed.

**Comment by marcosmenendez** [comment]
If someone uploads a picture with transparent background, the background is currently converted to black, but it should remain transparent

**Comment by JuanMenendezBuitrago** [comment]
I also changed the color so they match the site's palette (TGD red, TGD bue, and TGD green instead of regular red,blue and green). There's something about the design that doesn't look quite right though.

**Comment by marcosmenendez** [comment]
But are you going to improve it or is it ready to test?

**Comment by JuanMenendezBuitrago** [comment]
Someone deploy it to pre so I (or anyone) can test it properly. I can't do it myself I don't know why.

**Comment by atrandafir** [comment]
Deployed to pre finally and tested it. Great, transparency works!
