### ISSUE TITLE
Js error on Evil-Data page

### ISSUE THREAD

**Issue by atrandafir** [thegooddata/webapp#139]
Uncaught TypeError: Cannot read property 'value' of undefined

I'm testing on:
https://pre.thegooddata.org/evil-data

Logged in with admin user and I get a javascript error.

I think this error is only when user doesn't have certain data. 

But I think anyways we must test this and correctly test all the javascript variables before accesing them, or either always provide the json keys for that values with empty values.

**Comment by marcosmenendez** [comment]
I can only test that there is no error without data, but I cannot test that it works well with real data.

@atrandafir create that fake data please and test that this page is still working properly with data

**Comment by marcosmenendez** [comment]
Have you tested it @atrandafir ? Once done, please confirm here, close and deploy
