### ISSUE TITLE
Backend: advanced search differentiates capital and small letters

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#14]
And should not

**Comment by JuanMenendezBuitrago** [comment]
Where's advanced search in the webapp?

**Comment by JuanMenendezBuitrago** [comment]
I've made the necessary changes so that searches on text fields are case-insensitive but for some reason the advanced search in the members section does not work (not now and neither before the changes). I'll continue digging into it looking for what may be causing this behavior.
