### ISSUE TITLE
Stop sending admin data to piwik

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#142]
In piwik, if you go to action/pages, and you review last month data, you can see that it is a bit of a mess.

There is plenty of data generated in admin pages, both by the webapp, blog, and probably collaborate. We should avoid recording this data.

Check as well that it works well with blog, website and collaborate. Do some visits and confirm

**Comment by JuanMenendezBuitrago** [comment]
I removed the tracking code from the admin pages. In the blog, Piwik is configured so it doesn't insert the code in the admin pages and in OA I don't know if the same option is available. @josereyero can check that out.

**Comment by JuanMenendezBuitrago** [comment]
There's only pending for confirmation the part concerning @josereyero . The rest should be marked as   "closed".

**Comment by josereyero** [comment]
About Collaborate:
- It was already configured for not sending data from admin/* pages.
- I've done some review of the settings and excluded also data from users with the 'administrator' role.

Let me know if it's still sending any data it shouldn't.

**Comment by atrandafir** [comment]
@JuanMenendezBuitrago I've did a deploy to production and I'm viewing the Admin > Users list page and it has the Piwik JS code loaded if I view source code. Indeed some other admin pages don't have it. Maybe we should check this again.

**Comment by JuanMenendezBuitrago** [comment]
I forgot that Users had their own module so I think I just have to add a line to user/controllers/AdminController.php
