### ISSUE TITLE
Server Error when trying to get data from deleted accounts (SSO backend).

### ISSUE THREAD

**Issue by josereyero** [thegooddata/webapp#143]
Getting a server error from collaborate side when polling for user accounts that have been deleted on webapp: EXCEPTION 500:Internal Server Error

No functionality is affected, since this is not something that shouldn't happen as per our normal workflow (accounts are meant to be never removed, just marked as deleted / personal data cleaned up).
However I think this condition (polling for account that for whatever reason has been deleted by administrator) should be handled gracefully, some meaningful message should be returned from the server (webapp) to the client(collaborate).

Possibly in this case though not part of our regular user workflow we should be deleteting / cancelling also the related account in collaborate. The issue is that by not really handling this condition, we cannot tell from the client side (collaborate) whether we are polling a deleted account or there's any other error condition, server is temporarily down, etc...

Also from the server side, unless you keep some minimal account data I don't think it is possible to tell whether the account has been deleted or has never existed... Anyway, trying not to get into philosophy of existence :-), what I am asking here is a return message of the type: "User account Id not found" and we can  in turn take some action on the client side, possibly marking the account as "deleted" (Renaming to "Deleted account x", removing all related user data).

See client side log: https://collaborate-pre.thegooddata.org/admin/reports/event/60568

Related https://github.com/thegooddata/webapp/issues/54

**Comment by atrandafir** [comment]
This should be fixed in the next deploy since we are now automatically logging out users that were deleted in the webapp.

**Comment by atrandafir** [comment]
@josereyero Now it should be fine. On one side I've put a check to avoid accesing properties if the User was not found, and on other side I'm returning a not_found field with value 1 so in case you get that response you know that you have to delete the account.

**Comment by josereyero** [comment]
@atrandafir, thanks, that should work

Created a related issue to handle this new response, https://github.com/thegooddata/social/issues/41
