### ISSUE TITLE
Membership details bugs

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#145]
This is a follow-up of issue #20 regarding improvements to be done in membership detail page:

1- Image upload does not work. I've uploaded a png image, pressed on submit, and a blank page appeared. I went back and I saw a corrupted image as attached: 
![screen shot 2015-03-23 at 7 06 40 pm](https://cloud.githubusercontent.com/assets/1178350/6788190/cc216bbe-d18f-11e4-8d22-cc883587071a.png)

2- Once uploaded user has to be able to crop it with square proportions.
3- Change text that currently says "UNSUBSCRIBED" with "subscribed" in small letters, marked by default and a bit upwards, closer to the text that says "NOTIFICATION PREFERENCES"
4- Both the image, link and the notification preferences have to be editable in the "manage member" admin url
5- I'm pretty sure that changing the notification settings here does not update yet the settings in the collaboration website, so please change the question mark to: "Subscribe or unsubscribe from company newsletters (not from legal announcements)"
6- Could you please confirm that changes in this setting moves users between phplist segments 24 and 36 (if user is in pre-accepted status) and between segments 35 & 25 if the user is in accepted status?
7- Could you also confirm that if a user opts-out from a newsletter sent by phplist, we move him from one segment to another and we update the webapp membership details view?

Please respond here to points 6 & 7. If negative, please implement. @JuanMenendezBuitrago has worked with phplist and segments before, so ask him how he did it to maintain consistency

**Comment by atrandafir** [comment]
@bodiapz tested this and after several attempts I have managed to upload a picture of Monica Bellucci =)

But.. it still does not work smooth, the crop functionality doesn't show up for all pictures, just sometimes, and sometimes it doesn't and when submitting the form since there are no crop params passed the previews are not getting generated.

**Comment by marcosmenendez** [comment]
@atrandafir the crop still does not work properly. Could you please fix it? It seems @bodiapz has not been able to do it

The hoover next to each field is not working anymore either

**Comment by atrandafir** [comment]
I will first check if the latest changes were deployed to make sure there's nothing missing.
