### ISSUE TITLE
Queries duplicated

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#151]
Since last update search queries are being registered twice in the backend.

When fixing, please check that it works with google, yahoo and bing

**Comment by atrandafir** [comment]
I have tested this multiple times and it only stored one row for every search.

**Comment by marcosmenendez** [comment]
As mentioned above, it was linked to issue https://github.com/thegooddata/extension/issues/37 not sure if @JuanMenendezBuitrago has fix it already. If so, mark it as ready to test or, if in production, please close it

**Comment by JuanMenendezBuitrago** [comment]
I've been using the extension with the changes that I uploaded and I haven't had any duplicated queries either.

**Comment by marcosmenendez** [comment]
Does it mean that issue https://github.com/thegooddata/extension/issues/37 is already in production? in that clase, please close it. I close this one

**Comment by JuanMenendezBuitrago** [comment]
I don't know if they're in production. That's why I haven't closed this one or thegooddata/extension#37

**Comment by marcosmenendez** [comment]
So please check it yourself or with @atrandafir
