### ISSUE TITLE
Automatically calculate data trading revenues based on activity

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#153]
Since we can not rely anymore on Chango revenues, we will automatically ad data trading incomes daily based on sites visited and queries performed.

Every 24 hours we should count sites visited and queries performed during the day and run the following formula:

Data trading revenues of that day = sites visited that day  \* 0.00002 USD + queries performed that day \* 0.001 USD

**Comment by marcosmenendez** [comment]
Since @atrandafir is working on income related issues and I believe that @JuanMenendezBuitrago has not done anything on this issue, I reassign it to @atrandafir

**Comment by UchihaCFC** [comment]
@marcosmenendez This resulting amount does that show somewhere?, What view on /good-data with the other statistics?

@atrandafir the table on the database where visitors are stored is the achievements? and donations is loan's tables?

Thanks

**Comment by marcosmenendez** [comment]
Total incomes are shown here https://www.thegooddata.org/good-data
It is a summation of total donations and "data trading revenues". Donations will be updated automatically via stripe. I'm basically asking now to calculate as well "data trading" income daily using the formula above. If it is still not clear, pelase clarify with @atrandafir or call me via skype (marcosmenendez) or hangout

**Comment by JuanMenendezBuitrago** [comment]
Do you want to store those daily values in the tbl_incomes as a "Data trade" type? and if so, only from now on, or do you want to calculate/store those values for all the data we have?

**Comment by JuanMenendezBuitrago** [comment]
I've created a command that computes the daily income following the instructions you mentioned. This inserts a value into the tbl_incomes table, with type "Data trade" and source name "Queries plus visits". This command should be ran via a cron job  like either one the following:

    * 04 * * * /usr/bin/php /srv/webapp/current/protected/yiic.php ComputeDailyIncomes 1>&2

(output redirected to stderr)

    * 04 * * * /usr/bin/php /srv/webapp/current/protected/yiic.php ComputeDailyIncomes 1> /dev/null

(output ignored)

**Comment by marcosmenendez** [comment]
So? Who takes care of the cron job? you or @atrandafir ? If the second, then change assignee

**Comment by JuanMenendezBuitrago** [comment]
I think cron jobs are managed by Miguel unless @atrandafir has privileges to do so.

**Comment by calidadesystems** [comment]
just added in production machine, 

@JuanMenendezBuitrago  can give feedback tomorrow if it was correctly executed?

**Comment by JuanMenendezBuitrago** [comment]
Sorry about the delay... can yo add it in preproduction?... I don't want to test it with production data.
Thanks.

**Comment by calidadesystems** [comment]
added in preproduction and disabled in production, waiting for a successful  results

**Comment by JuanMenendezBuitrago** [comment]
thanks :)

2015-08-27 18:43 GMT+02:00 Calidade Systems <notifications@github.com>:

**Comment by marcosmenendez** [comment]
I haven't seen any quantity automatically added in the last month. @JuanMenendezBuitrago can you check what's going on?
