### ISSUE TITLE
Change user default settings: Store navigation data and Trade non-sensitive data

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#155]
Since we are not working anymore with chango, we should mark all users not to trade non sensitive queries. This issue is linked to these other 2:
https://github.com/thegooddata/webapp/issues/158
https://github.com/thegooddata/extension/issues/41

On the other hand, in order to get enough relevant data to analyse we need to store navigation data by default (both browsing and search history).

Let's do it for new users only, keeping existing users preference unchanged in that regard.

We must make sure that we don't store any sensitive search or browsing history. We should not store either non-english search queries

**Comment by atrandafir** [comment]
Trading totally disabled.
