### ISSUE TITLE
Delete trading data brokers

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#158]
Since we are not working anymore with chango, we should mark the list of data brokers they work with as "blocked", instead of "trading". They were 20 or so

We should keep the functionality in case we want to use it in the future

**Comment by atrandafir** [comment]
Trading data brokers are now blocked when trading feature is disabled from code.

https://github.com/thegooddata/extension/commit/1daf74fc84108815b2a5dbf582fced280f22f620
