### ISSUE TITLE
Delete references to authors

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#159]
I've seen in the code some emails of coders like raulgalindo. Since the code is open and all commits and authors are public on github I don't see the point of leaving those details in the code, unless we make sure that we put the emails of everyone that has contributed (which is a bit unsustainable).

We should delete therefore these personal references in the code. Both in the extension and the webapp

**Comment by JuanMenendezBuitrago** [comment]
I'll take care of it.

**Comment by JuanMenendezBuitrago** [comment]
Under what license are we publishing the code? I'm not sure if we can remove author information in every case.

**Comment by marcosmenendez** [comment]
I'm not asking to remove copyright info about disconnect or thegooddata,
but about the developers that thegooddata has hired. The code is owned by
the company, not by their employees/contractors



*Marcos Menendez*
hangout: marcos@thegooddata.org
skype: marcosmenendez
tel: +44 (0)20 3289 0009
twitter: @marcmenen <https://twitter.com/intent/user?screen_name=marcmenen>
Unit 1, 82 Clerkenwell Road
London EC1M 5RF

**Comment by JuanMenendezBuitrago** [comment]
Understood

**Comment by marcosmenendez** [comment]
To be consistent with previous policy we have agreed to maintain authors as well as copyright in all files (issue #172)
