### ISSUE TITLE
Minor piwik issues

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#161]
I've seen that we are not in the latest version. I would like to update it myself, but not sure that if I do, everything will crash. Please update it and ensure that I can update it with no help in the future

If you visit admin/settings/system check there are some minor errors that should be fixed.

I've never received an email so I just included smtp info. I hope it works

**Comment by agonbar** [comment]
For some reason my chrome deleted the password of piwik from the database,
would you mine sending me the credentials? Thank you.

**Comment by agonbar** [comment]
The automatic installer works like a charm, only needs to do the database upgrade manually in case it gets too big, but I don't think we could ever reach that size. For future problems I've saved the command to do the database upgrade manually, so @marcosmenendez can do always the upgrade and if it fails I finish it in a minute.

**Comment by marcosmenendez** [comment]
Still I'm not receiving any emails from piwik, although I signed up for the activity report. Is it working?

**Comment by agonbar** [comment]
It should as the configuration is ok, i'll test it this afternoon then.

**Comment by marcosmenendez** [comment]
Any news? I still don't receive any weekly report (as configured).

If I force piwik to send it, I get the following message:
![screen shot 2015-06-07 at 10 59 58 am](https://cloud.githubusercontent.com/assets/1178350/8023270/6fd2dbf8-0d04-11e5-8a09-76eb675ec666.png)

**Comment by agonbar** [comment]
I'm searching the logs to find the problem. Its a slow process, but the
only way.

**Comment by agonbar** [comment]
It should work now, always let the e-mails be sent by the default configuration as the relay does well the job.

**Comment by marcosmenendez** [comment]
I haven't receive any weekly report yet.

**Comment by agonbar** [comment]
It seems the piwik reports have a bug in the last update. In their forums they recomend a reinstall, do we have any special file changed like in phplist? If not, I'll wipe this installation and place the latest version.

**Comment by JuanMenendezBuitrago** [comment]
Let me know when you have done the reinstallation so I can upload the changes made in the CSS.

**Comment by marcosmenendez** [comment]
@agonbar is this issue solved? Can @JuanMenendezBuitrago upload css changes?

**Comment by agonbar** [comment]
Upload them, it's safe to do it. The problem is still there but it can be
solved without reinstalling anymore.

**Comment by marcosmenendez** [comment]
I haven't receive any weekly report yet by email. Please fix!

**Comment by agonbar** [comment]
I was told there was a new guy to do everything and has the users and
passwords to access, tought I don't know his github account. Maybe someone
at Openhost knows.

**Comment by calidadesystems** [comment]
I've just updated piwik to latest version avaliable, and email reports are working through amazon.
