### ISSUE TITLE
Review partners page and faqs to take out references to data trading

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#163]
Since we are not trading data anymore, we should change those texts. Whoever takes this issue, please ask me for the new texts

**Comment by JuanMenendezBuitrago** [comment]
Send me the details.

**Comment by marcosmenendez** [comment]
Home:
Our donors reward your care with your data. We reinvest 50% of these donations
into TheGoodData, and the other 50% fund microloans to people in developing countries via our partner, Zidisha.
ABOUT OUR GOOD DATA (link to good-data)

Partners page: delete it and take it out from unlogged menu

Product page (fix the indent of points 3 & 4):
2. We process your data securely:
- If you give us permission, we anonymize and store your browsing history and search queries for a limited period of time (3 months).
- This valuable information will help us build reports identifying good and evil players in terms of online tracking. We will publish them as soon as we have enough volume of users.
- We never store any queries which contain sensitive terms - health, sexual, religious, political or financial scoring - so that you can rest easy about that.
- You can access or delete any of your stored information at any time. 

3. We raise money thanks to your data
- At this point we are not trading any anonymous browsing data anymore. Problems with Google Webstore have forced us to postpone this option until we manage a higher volume of users & traffic.
- In the meantime we are raising funds from private donors that are sponsoring our users care with their data without getting anything in exchange (no one access your data).
- We believe in data consent and respect. If you are interested in sponsoring or buying our users’ anonymized data you can contact us at: data@thegooddata.org

4. We reinvest our earnings for everybody's benefit
- We reinvest 50% of the money raised in projects run in developing countries by Zidisha, the person-to-person microcredit leader.
- We invest the other 50% in developing new features for TheGoodData, protecting your data and ensuring our mission is on track.

FAQs:
Read and apply June 29th, 2015 changes here: https://docs.google.com/document/d/1Z5IjLa177QKiNXd37G_durBf0udfxt03XrA6O9tGMSw/

**Comment by JuanMenendezBuitrago** [comment]
I don't understand the ordered list. Where is this list supposed to be inserted?

**Comment by marcosmenendez** [comment]
I have written bullets instead of numbers, but github reformats it automatically without letting me change it. Let me copy numbers 3  & 4. Bullets for 2nd tab are fine:

3. We raise money thanks to your data:
* At this point we are not trading any anonymous browsing data anymore. Problems with Google Webstore have forced us to postpone this option until we manage a higher volume of users & traffic.
* In the meantime we are raising funds from private donors that are sponsoring our users care with their data without getting anything in exchange (no one access your data).
* We believe in data consent and respect. If you are interested in sponsoring or buying our users’ anonymized data you can contact us at: data@thegooddata.org

4. We reinvest our earnings for everybody's benefit
* We reinvest 50% of the money raised in projects run in developing countries by Zidisha, the person-to-person microcredit leader.
* We invest the other 50% in developing new features for TheGoodData, protecting your data and ensuring our mission is on track.

**Comment by JuanMenendezBuitrago** [comment]
Should the latest revision date in the FAQs be set to June 2015 instead of January 2015?

**Comment by marcosmenendez** [comment]
Yes
