### ISSUE TITLE
New subscribers not properly added into phplist

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#168]
When adding a subscribers into phplist, there is a field called "Send this subscriber HTML emails" that should be set to 1 by default. Since March 7th all new subscribers are created with this variable set to blank, so they are excluded from all mails.

I will manually fix it for the "Members legal comms" since I have to send a newsletter right away, but please change it for all users and ensure new ads are properly marked as 1

**Comment by marcosmenendez** [comment]
There is another field called "Is this account disabled?" that i think should be marked as 0 by default. Please check all fields

**Comment by JuanMenendezBuitrago** [comment]
I've fixed the issue and updated all records in the database so htmlemail is set to 1 and disabled set to 0
