### ISSUE TITLE
Check that company achievements data is correct

### ISSUE THREAD

**Issue by atrandafir** [thegooddata/webapp#171]
We should check in the database that the information is correct:

1,219,246
Monthly Visits Stored
1,176,183
Monthly Threats Blocked
8,295
Monthly Queries Traded

**Comment by UchihaCFC** [comment]
The data do not match, when I refreshed the cache completely erasing the ranks of the table YiiCache database to refresh the page numbers have changed and match. It does not happen only with the data of the month, also happens with registered and active users, etc .. shown in the same column.

I added in a push commit to develop branch, a cache flush and delimited seconds it takes for a query to the database to also reduce waiting time, related to issue #169  when I got a limited time this query is not trapped.

**Comment by atrandafir** [comment]
- Fixed one bug with the data because UsageDataDaily was duplicating some records.
- Verified the production database and the numbers are correct, we've got 1102608 blocked adtracks and about 1897756 allowed.

**Comment by marcosmenendez** [comment]
Regarding "Monthly visits" metric, what do we count as a visit? every single page visited? Every domain visited? I guess it is the first, in that case we should call it "Monthly Pages Stored". Could I get by email a random list of 1,000 of those visits? just want to check the kind of info that is there. Thanks

**Comment by UchihaCFC** [comment]
Missing: More testing in the form of stored data, real testing, etc... in Visits and Adtracks

**Comment by marcosmenendez** [comment]
And change Monthly visits" with "Monthly page views"
