### ISSUE TITLE
Change Queries traded figure with queries run

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#176]
Since we no longer trade user queries, we should not show anymore that figure in the good-data page, showing instead the Monthly Queries Run.

We should also change the order of Threats Blocked and visits stored. Show first the threats

**Comment by marcosmenendez** [comment]
@UchihaCFC Could you fix it when doing issue #171 ?

**Comment by marcosmenendez** [comment]
@JuanMenendezBuitrago I don't see this change deployed. If t hasn't been deployed by @atrandafir, please reopen (and do so with similar issues not deployed)

**Comment by JuanMenendezBuitrago** [comment]
This issue is deployed in preproduction.
