### ISSUE TITLE
Delete loan identifier field

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#178]
Each loan has currently 2 ID: the loan ID and the loan identifier. We should get rid of the second. Delete it from the database and take it our from the loan views like https://www.thegooddata.org/loans/admin

**Comment by JuanMenendezBuitrago** [comment]
OK. That loan_identifier is used to name the image files for each loan so I'll have to rename the images already created. I can use the id for that unless you prefer some other way.

**Comment by marcosmenendez** [comment]
id is ok

**Comment by JuanMenendezBuitrago** [comment]
Deployed to preproduction.
