### ISSUE TITLE
Lot of syntax errors in nginx

### ISSUE THREAD

**Issue by calidadesystems** [thegooddata/webapp#179]
Hello to all, new relic is sending warnings about errors, systems are working well but i see a lot of request like POST /api/<something> HTTP/1.1 with this error

PHP message: PHP Parse error:  syntax error, unexpected 'CONST' (T_CONST), expecting ',' or ';' in /srv/webapp/shared/config.php on line 110

file /srv/webapp/shared/config.php  appears to be ok and checking it with lint gives an ok

php5 -l /srv/webapp/shared/config.php
No syntax errors detected in /srv/webapp/shared/config.php

line 110 of /srv/webapp/shared/config.php
 contains this value
CONST SHOW_NEW_LANDING = TRUE;

**Comment by jorgeheavydots** [comment]
Good day and thanks for your mail.

I was deploying a new landing and add a new constant to the config.php 
file but didn't notice there was a missing semicolon. I just fixed it.

Thanks again

**Comment by calidadesystems** [comment]
@jorgeheavydots Sysadmin policedepartament is watching you  :-P
Thanks for your response
