### ISSUE TITLE
Changes on footer

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#182]
There are some small changes to be done in the footer:
1. Update legal address to 7-15 Greatorex Street London E1 5NF
2. Take out the copyright text
3. Move 2 icons right below the other 2. Clockwise from upper-left: TGD, twitter, reddit, wordpress
4. Put "Coders" in the place of "Support" and eliminate "Third parties" column
5. Stretch all the columns to leave some more space at the right hand side
6. Put there the Creative Commons icon, and right below the text. Make the icon clickable as well

**Comment by JuanMenendezBuitrago** [comment]
The result looks like this but the social icons look a bit awkward. They fit in a single row as they were before, in case you like them better like that.

![tgd-footer](https://cloud.githubusercontent.com/assets/5305439/10284647/4ec60c2a-6b85-11e5-9b56-f18fdee43cf1.PNG)

**Comment by marcosmenendez** [comment]
ok. Let's leave it in one line. Thanks
