### ISSUE TITLE
Check monthly pages and threats

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#188]
After last fix those numbers look a bit higher than in the past. If we do some maths and divide pages visited by active users, it shows than an average user visits 500 pages per day including weekends. That's too high.

Are we counting visits and users correctly? It may well be that we are duplicating some pages visited, or counting browser actions like new tabs, etc

**Comment by jorgerayware** [comment]
I've been looking into this issue and apparently there is a bug in the extension, since its gathering data without a member_id nor user_id. This is what is messing with visits counter. I'll keep on touch with it.

**Comment by JuanMenendezBuitrago** [comment]
There's some data sent from the extension that doesn't have member_id no user_id information attached to it. I'm not sure if it only happens for browsed pages or if it happens for threats too, but t is made on purpose when the user is not logged in (I guess). I think that Bogdan worked on this but Maybe Alex can give some more info about it.

**Comment by atrandafir** [comment]
I think you are right @JuanMenendezBuitrago! I've forgot about that. I think this was the related issue in the extension: https://github.com/thegooddata/extension/issues/33

**Comment by marcosmenendez** [comment]
Still we need to count those users. We cannot count one thing (pages) and
not the other (users).
The requirement was to count both, but don't store details on that activity
(domains visited, etc)

**Comment by marcosmenendez** [comment]
Besides fixing that, as said at the issue, the number of pages visited have
grown significantly without any growth on the user side. Once fixed the
user count, we should check that there is no user with a significant number
of visits besides admin user.

In the past there was a hacker that decided to create fake users for fun.
It may well be that there is a hacker creating fake visits. Let's check that
