### ISSUE TITLE
Use friendly links only

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#24]
Each page has a long and a friendly url. We should use the friendly versions only. Most of the times, when there is an error (when signing in or when applying for membership for example) the user is sent from the friendly url to the long one.

Share purchase link that is presented both in the acceptance email and in the menu uses the long version (https://www.thegooddata.org/user/purchase) instead of the short one (https://www.thegooddata.org/share)

**Comment by atrandafir** [comment]
Just checked and all the urls look fine to me, if we ever find one that has this problem just create a new issue to fix it. Closing.
