### ISSUE TITLE
Delete user data automatically

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#54]
We should keep as minimum data as possible. The following automatic processes should be implemented. Split them into separate issues if some of them are more complex and will require some more time to investigate:
1. Delete all usage data that is older than 3 months except the totals needed to show yearly figures (we can keep just daily totals and sum up to calculate last year's)
2. Delete all user data of those members that have been inactive for more than 3 months
3. Delete all usage data automatically when a member resigns
4. Delete all user and member data of members 1 month after resignation
5. Delete all user and member data if they have been inactive more than 6 months (at the end of the month 3 we should send an automatic email warning about it)

By usage data I understand browsing and search history
By user data I mean user id, blocking and whitelist preference, etc
By member data I mean username and email as well as PII

In order to delete all member PII data we will need to unencript it manually first

When deleting user data, average data should be kept so we can still draw monthly and anual graphs

**Comment by bodiapz** [comment]
I'm doing like @josereyero said. I will truncate user privat data, and put there Deleted user # mark

**Comment by marcosmenendez** [comment]
Need to delete it. We cannot keep data that should have been deleted

**Comment by josereyero** [comment]
@marcosmenendez,
Well, the idea is we do delete user data, though we are keeping the "account" (as a number without personal data) for reference and synchronization purposes.

**Comment by atrandafir** [comment]
Hi @bodiapz , just tried to apply the latest database migrations locally and it gives errors. 

Sorry because my postgresql installation is in Spanish.

Can you confirm that the scripts to create the last views are correct as you have them?

				 ...exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42601]: Syntax error: 7 ERROR:  no se pued
		en insertar m+¦ltiples +¦rdenes en una sentencia preparada. The SQL statement executed was:
					DROP VIEW view_adtracks_members;
					CREATE OR REPLACE VIEW view_adtracks_members AS
					 SELECT member_id, domain, SUM(adtracks) as adtracks FROM (
						 SELECT tbl_adtracks.member_id,
							tbl_adtracks.domain,
							count(*) AS adtracks
						   FROM tbl_adtracks
						  GROUP BY tbl_adtracks.domain, tbl_adtracks.member_id

						  UNION SELECT member_id,
							domain,
							value AS adtracks
						   FROM tbl_usage_data_domain
						   WHERE name = 'adtracks'
						  ) a
						  GROUP BY domain, member_id
						  ORDER BY adtracks
