### ISSUE TITLE
Money repaid and available for microloans not properly calculated

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#60]
I've updated info of loan here https://www.thegooddata.org/loans/update/4 adding $5.74 paid back. However, if I go to Good Data https://www.thegooddata.org/good-data I don't see that amount in "Money repaid". Money repaid should be the summation of money paid back of every loan

Regarding Money available for microloans, it should be the sumation of Income * Money reserved minus the summation of money lost of the different loans

**Comment by atrandafir** [comment]
Set the fields to 0,

**Comment by marcosmenendez** [comment]
Money available for microloans should not include expenses. That means that it equals
Sumation of ((income - expenses) * money reserved/100)
