### ISSUE TITLE
[Interest] Import Alexa categories of most visited sites

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#82]
We will ad some graphs to the user data showing user interest based on browsing habits.

Before that, we have to categorise their browsing habits

To do that, we need to have the categories of the most visited sites. We will use Alexa Top sites API http://aws.amazon.com/es/documentation/alexa-top-sites/

Take into account that categories include sub-categories as well (and subsequent levels). Those sub-categories may depend upon one or multiple categories of the upper level or higher (not lower).

We can call them Interest-categories and create a table to change their name (in multiple languages) and dependencies from the admin website.

After this step, I'll ad other issues to explain how will we calculate user profile, and how we will present it. Next issue is #87

**Comment by bodiapz** [comment]
As I understand, we should copy all categories tree localy, right?
Should we identify site category via Alexa API or other way?

**Comment by marcosmenendez** [comment]
Yes, we should better copy all categories and subcategories locally, and then cross check the domains the user visitor against Alexa categorizarion.

I don't imagine other way to categorize besides Alexa. If you suggest a better way, I'm open to it

**Comment by marcosmenendez** [comment]
Regarding the API, we have seen that using PHP for the APIs that connect webapp to the extension demands a lot of resources. Could we use node.js? Does it makes sense? Do you have experience on it?

**Comment by bodiapz** [comment]
I'm not feel comfortable with node.js and I'm not really sure the node.js will improve performance. 
I suggest grab site category in extension, using user resources, and send into webapp API site name and category.
If will you approve this way I learn how to do this.

**Comment by marcosmenendez** [comment]
@atrandafir can you share your thoughts on this? Not sure that I understood well, but if we are going to store all Alexa categories in the extension, and we sum up sensitive keywords storage, we may be demanding too many user resources, wouldn't we?

@bodiapz how big is that database?

**Comment by atrandafir** [comment]
Hi both,

I took a look on the API link you provided and as far as I can see that API provides just information about a domain, and not even the category.

I cannot see a way of getting all Alexa categories unless there's other API.

So first we should make sure of the third party service we're using to identify websites categories and:
1. See if they provide a full categories list that we can download and import, or we have to enter them manually
2. See if they have a batch mode to get information on multiple domains to know their category

Once that's decided, either with Alexa or other service:

1. We could create a local table for domains
2. Every time someone visits a new domain that we don't have in the db, we will insert it into the table with a NULL category
3. We setup a daily cron job that will make requests to the third party service that will tell us what are the categories for the new domains

So this means there's no extra resource usage either from extension or webapp, just in the webapp checking if domain exists or not already in the table.

So let's see if Alexa provides the info or if we need to look for another service, or, don't use a third party service and instead make our own categories and categorize them either from admin or with collaboration of users  of thegooddata.

**Comment by marcosmenendez** [comment]
Alexa provides the info and it is the best source for that. That's the reason I'm requesting it.

Agree with @atrandafir approach with one caveat: Alexa does not classify all websites, just the largest ones, so there should be 2 status for domains: Null and NA (Not available) so we don't keep on requesting the category for a domain that they do not cover.

**Comment by bodiapz** [comment]
As I understand:
1. We copy all categories tree locally
2. Every a new site stored in some new table with "category = NULL"
3. Every day cron update categories via Alexa API
4. Other cron every day recalculate "visited" counter for each category

Am I right understood?

**Comment by marcosmenendez** [comment]
Unless you propose something different @bodiapz 
But my comment is still missing, don't request everyday the category of those sites that Alexa do not cover. Do it as you want

**Comment by bodiapz** [comment]
Problem while importing categories... Alexa bans my IP very often. I'm jumping through VPNs, and I've set timeout 10 seconds between scanning. 

But there are millions of categories, so in fact with 10 sec timeout it will scan around few months. Maybe, not need grab all category tree, just top categories level, and few (3 - 4) sublevels.

For example

All Categories > Science > Biology > Flora and Fauna > Animalia > Arthropoda > Insecta > Hymenoptera > Apocrita > Formicidae > Formicinae

so maybe we can categorize the site into "Flora and Fauna" category, instead of separate so many categories?

I'm stuck on this issue.

**Comment by marcosmenendez** [comment]
Yes please. Do so

On Thursday, February 12, 2015, bodiapz <notifications@github.com> wrote:

> Problem while importing categories... Alexa bans my IP very often. I'm
> jumping through VPNs, and I've set timeout 10 seconds between scanning.
>
> But there are millions of categories, so in fact with 10 sec timeout it
> will scan around few months. Maybe, not need grab all category tree, just
> top categories level, and few (3 - 4) sublevels.
>
> For example
>
> All Categories > Science > Biology > Flora and Fauna > Animalia >
> Arthropoda > Insecta > Hymenoptera > Apocrita > Formicidae > Formicinae
>
> so maybe we can categorize the site into "Flora and Fauna" category,
> instead of separate so many categories?
>
> I'm stuck on this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thegooddata/webapp/issues/82#issuecomment-74034948>.
>


-- 


*Marcos Menendez*
hangout: marcos@thegooddata.org
skype: marcosmenendez
tel: +44 (0)20 3289 0009
twitter: @marcmenen <https://twitter.com/intent/user?screen_name=marcmenen>
Unit 1, 82 Clerkenwell Road
London EC1M 5RF

**Comment by marcosmenendez** [comment]
@bodiapz When you manage to download that list, please send me the csv to take a look. Just curious.

If you are still having problems getting it, please tell me and I'll ask some people that did it in the past.

**Comment by marcosmenendez** [comment]
@bodiapz I don't see a link to access this table in the admin site as requested

**Comment by bodiapz** [comment]
Marcos you are right, I've missed this table. I will provide it in closest time. 
But I have a question here. How should look translation functionality? I mean you want to be able to translate any category to any language?

**Comment by marcosmenendez** [comment]
Yes. Just the category name. We will only use English at start, but should
be ready for international

**Comment by bodiapz** [comment]
I've done only viewing table. For multi language I need to know how we will implement multi language support. Is there will be some i18n plugin, or we will manually develop functionality.
