### ISSUE TITLE
[Interest] Calculate average and individual interests

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#87]
We should calculate the average behaviour of our users by calculating the share of urls visited for each subcategory at the lowest level (upper levels are calculated adding percentages of each sub-level).

For the time being let's do it using the last 7 days of data and calculate it every 24h. Data should be cached to avoid unnecessary calculations. We can store this percentage in a variable of interest-category called 7-day-avg.

Lets do the same for each individual.

Based on that data we will decide on the threshold that we should establish to determine if a user is relatively more interested in a specific category than our average user. We will determine that in a separate issue

**Comment by marcosmenendez** [comment]
I add here a screenshot of how this interest should be calculated in my opinion. Open to discuss specially if we think that it may cause unnecessary server resources
![interest calculation](https://cloud.githubusercontent.com/assets/1178350/6439185/948198ac-c0d0-11e4-8132-1a2f9711d6b8.jpg)
It basically calculates the interest of a person on a given category looking at the percentile that person is comparing with the rest of the users. This percentile is calculated based on the % of pages visited for a given category.
If that person is percentile 80, it means that its rating is +60 (80-50)*2.
If that person is percentile 30, its rating is -40

**Comment by bodiapz** [comment]
Marcos, we already discussed this, but I'm confused on one line. Line 36|55|.......|28|. 
All other I understand totally, but on this line I have doubt. Can you write to me again how we should calculate this numbers. 

Thanks in advance

**Comment by marcosmenendez** [comment]
Bodia, that's the percentile comparing the percentage of time spent to all other users.

The fact that a user spend, let's say 5% of the time watching sports site is not meaningful if we don't compare it to the other users. Let's imagine that there are 50 users that spend below 5% of their time in sports sites and 50 other users that spend more than 5%. That would mean that this user is percentile 50. So he has no particular interest on sports comparing to the other users. I think Postgre provides a function to get this number. We have used it elsewhere in the site (in evil data for instance)

**Comment by bodiapz** [comment]
Thanks. I've done like you've described. I hope this time my commit will be
good

2015-03-12 14:35 GMT+02:00 Marcos Menendez <notifications@github.com>:
