### ISSUE TITLE
Install minScript extension and modify the way we load all assets

### ISSUE THREAD

**Issue by atrandafir** [thegooddata/webapp#88]
In order to minimize and unify assets and also avoid browser cache and serve always the most recent version we must install minScript extension.

Once the extension is installed, all the javascripts and css files in the layout must be updated to be loaded with Yii::app()->clientScript so that minScript extension takes them into account.

Also some testing must be done while we change this in order to make sure nothing gets broken.

**Comment by bodiapz** [comment]
Issue closed. I've tested on my local machines. And seems all fine

**Comment by atrandafir** [comment]
I'm repeating here the comments I have did on your commit on this issue in case you missed them:

1. If you remember we talked that the configuration must be duplicated for all 4 configuration files and that you can create separate common files and include them. So please fix that, make sure the configuration is repeated in all 4 files otherwise when publishing to production or pre environment the configuration will be missing.

2. Why did the jquery script file name changed from jquery-1.9.1.min.js to jquery-1.9111.1.min.js? Just curious..
