### ISSUE TITLE
The blog is not sending emails

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#92]
When new comments are posted, the blog should be sending a notification email to marcos@thegooddata but it is not doing it

**Comment by agonbar** [comment]
It should be fixed, but i can't test it without Marcos. Will revise on next meeting.

**Comment by agonbar** [comment]
To solve the problem I need either a google mail acount (gmail, google services) or any smtp server with an account (the mails will only go to Marcos, so there's no need to use Amazon SES).
@marcosmenendez  please send me an email as soon as possible with username and password.

**Comment by marcosmenendez** [comment]
You can use Amazon SES

**Comment by agonbar** [comment]
Ok, i'll configure it then.

**Comment by agonbar** [comment]
This has been solved and tested with marcos, closing the issue.
