### ISSUE TITLE
Country should be registered with latin caracters

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#97]
As you can see in member 7370278 country name has been saved using Cyrillic alphabet. We can let him introduce the country in such characters, but then we should convert it to the standard list of countries that we have

**Comment by marcosmenendez** [comment]
Not only that, but country name should be in English always. Currently there are people with Spain or España. All of them should be with Spain

**Comment by JuanMenendezBuitrago** [comment]
OK, so what alphabets should we be able to deal with, apart from Cyrillic (japanese, chinese... ?)

**Comment by marcosmenendez** [comment]
All. Either that or we convert them to latin. I don't know what is the standard procedure for international sites

**Comment by JuanMenendezBuitrago** [comment]
Google Maps API returns the country data in two formats: long (the real name, using the alphabet determined by the user's settings) and short (UK, US, ES, FR).
I'm still trying to figure out if the short format is also affected by the user's language settings.

**Comment by marcosmenendez** [comment]
It probably follows ISO standard, doesn't it? https://www.iso.org/obp/ui/
