### ISSUE TITLE
Install Piwik analytics

### ISSUE THREAD

**Issue by marcosmenendez** [thegooddata/webapp#98]
Download it from here: http://piwik.org/download/ (requires 5 minute installation)

Take into account recommendations to avoid cookie consent explained here: http://piwik.org/blog/2014/10/cnil-recommends-piwik-analytics-tool-no-cookie-consent/

(1) anonymise visitor IP addresses (at least two bytes)
(2) include the opt-out iframe solution in your website.

Once deployed, send name and description of cookies to @JuanMenendezBuitrago so he can add them in the cookie policy within the privacy policy

**Comment by agonbar** [comment]
piwik.thegooddata.org is now working, but the webs to be tracked still need to be configured by adding a script.
http://developer.piwik.org/guides/tracking-javascript-guide
There's the guide to do it, it's adding that code to the footer. I'll assign Alex to do it.

**Comment by JuanMenendezBuitrago** [comment]
I've added the script to the layout footer in the webapp's pages with the three options available in the piwik admin settings page.

**Comment by marcosmenendez** [comment]
Juan, have you added cookie information in the privacy policy as requested?

script should not only be added in the webapp, but in the collaboration and blog pages as well. Has it been added there as well?

**Comment by JuanMenendezBuitrago** [comment]
I fixed the error in the WP plugin settings and I think it works well now at least as far as inserting the link to the javascript is concerned. It recorded my visits but I didn't go deep into the rest of setting options which I will do next. There's another plugin available for Drupal that we could use for the OA pages. 

About the cookies, I've identified 4 related to Piwik: PHPSESSID, PIWIK_SESSID, _pk_ses.1.c6c5, _pk_id.1.c6c5	. The last two I think they're not always the same but instead follow a certain pattern, each one begining with "_pk_ses." and "_pk_id." and then by two values separated by dots.

**Comment by marcosmenendez** [comment]
In the privacy policy we need to:
1. mention all these cookies. Also the piwik_ignore mentioned here: http://piwik.org/faq/general/faq_146/
2. set this iframe so users can opt-out: http://piwik.org/docs/privacy/#step-3-include-a-web-analytics-opt-out-feature-on-your-site-using-an-iframe

**Comment by agonbar** [comment]
Initially piwik was installed using the guide to avoid cookies, so using
them like it says in the guide should be imposible.

**Comment by JuanMenendezBuitrago** [comment]
![cookies](https://cloud.githubusercontent.com/assets/5305439/5942483/369909f4-a718-11e4-95c6-4a7ce39c2a81.PNG)
![optout](https://cloud.githubusercontent.com/assets/5305439/5942519/64e28ed4-a718-11e4-9f94-69a13b105eb7.PNG)

**Comment by marcosmenendez** [comment]
Opt-out message seems hidden since it is in the very bottom of the page. I may be misleading as well since it may be understood that you are opting out of every cookie in the page. Can we put it inside the last box that describe piwik cookies?

**Comment by JuanMenendezBuitrago** [comment]
![optout2](https://cloud.githubusercontent.com/assets/5305439/5956561/6c2a9442-a7af-11e4-974f-dc29c7d5822d.PNG)

**Comment by marcosmenendez** [comment]
Good.

@agonbar could you give as an estimate of when can piwik work as requested at the top of the issue? (I guess standard installation will work since we are already hashing the IP Thanks

**Comment by JuanMenendezBuitrago** [comment]
The OA module for Piwik is still pending. Is Jose still working on the OA side? I mean, the module has to be installed through an admin account or using features, and I think Jose suggested using features because it made unnecessary to dump/backup the database when pulling the code from git.

**Comment by marcosmenendez** [comment]
@josereyero can you take care of this, please?

**Comment by josereyero** [comment]
Ok, I'll give a try to the Piwik module, https://www.drupal.org/project/piwik

**Comment by josereyero** [comment]
Could someone please send me the configuration for it? (Site ID, Piwik URL...)

Btw, this has a lot of other options: which roles to track -I'll assume all but admins-, track downloads, search keywords... Are we using some common options for all sites or should I just set some defaults?

**Comment by JuanMenendezBuitrago** [comment]
Do you still need it? I was going to look it up in the settings but it seems like @marcosmenendez changed the login credentials so you better ask him directly.

**Comment by JuanMenendezBuitrago** [comment]
Site ID shoud be: 3
And piwik URL: https://piwik.thegooddata.org

**Comment by JuanMenendezBuitrago** [comment]
@josereyero , can you cha

**Comment by JuanMenendezBuitrago** [comment]
@josereyero can you change the siteID to 1? and enable tracking across subdomains if there's such option available. I'll do the same in the blog plugin so that one siteID analyzes blog, www and collaborate ... and see what happens.

**Comment by JuanMenendezBuitrago** [comment]
Which user roles do you want to track in the blog?
![filterpiwik](https://cloud.githubusercontent.com/assets/5305439/6019287/171d629c-ab9f-11e4-908c-6c9042d4269c.PNG)

**Comment by marcosmenendez** [comment]
@JuanMenendezBuitrago it was already set up. Only subscribers should be tracked

**Comment by josereyero** [comment]
Ok, enabled in collaborate / production site with the following settings:
- Site ID = 1
- One domain with multiple subdomains
- Track All roles but admin & editor
- Disabled Track User ID
(There's some opt-out for user accounts, disabled)
- Enabled: Universal web tracking opt-out
- Set javascript scope to: Footer

Deployed along with some security update for a module.

Just wondering: should I add that opt-out iframe somewhere in the site?

**Comment by agonbar** [comment]
Sorry, there was no conection in my phone while I was in openhost.
The cookies are set to use primary ones but block all the third party ones
like I said some emails ago. There should not need any change if everything
works.
The only task still pending is changing de geoip module to use the C one
instead the php, but I need to unify three config files so I'll do it while
resolving other task to consume less hours.

**Comment by marcosmenendez** [comment]
@josereyero the opt-out iframe that @JuanMenendezBuitrago should have to work for all subdomains including blog and collaborate. Does it work that way? If not, is there a way to make it work with one single opt-out?
